config/routes.rb
Rails.application.routes.draw do
  root "ideas#index"
  get "/signup" => "users#new"
  get "/login"  => "sessions#new"
  delete "/logout" => "sessions#destroy"

  resources :sessions, only: [:create]
  resources :users
  resources :ideas do
    resources :comments, only: [:create]
    # TODO: refactor the idea routes, they read ugly
    resources :idea_members, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Idea do |idea|
      idea.user == user
    end

    can :manage, Comment do |comment|
      comment.user == user
    end

  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea
  
  validates :body, presence: true, uniqueness: { scope: :idea_id }
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  # membership
  has_many :idea_members
  has_many :member_users, through: :idea_members, source: :user

  # likes
  has_many :likes
  has_many :liking_users, through: :likes, source: :user

  validates :title, presence: true, uniqueness: { scope: :user_id }
  validates :description, presence: true

  # images
  mount_uploader :image, IdeaImageUploader

  # Decorator methods
  def self.all_by_date
    all.order("created_at DESC")
  end

  def description_truncate(len)
    if description.length > len
      "#{description[0..len]}..."
    else
      description
    end
  end

  def creator_username
    creator_user.username
  end

  def creator_user
    user
  end

  def comments_by_date
    comments.all.order("created_at DESC")
  end

  def num_members
    idea_members.count
  end

  def members_include?(user)
    member_users.include? user
  end

  def membership_for(user)
    idea_members.find_by_user_id(user.id)
  end

  def num_likes
    likes.count
  end

  def liked_by?(user)
    like_for(user).present?
  end

  def like_for(user)
    likes.find_by_user_id(user.id)
  end
end

app/models/idea_member.rb
class IdeaMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  validates :user_id, uniqueness: { scope: :idea_id }
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :idea

  validates :user_id, uniqueness: { scope: :idea_id }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :ideas

  # membership
  has_many :idea_members
  has_many :idea_memberships, through: :idea_members, source: :idea

  # likes
  has_many :likes
  has_many :liked_ideas, through: :likes, source: :idea

  has_secure_password

  validates :username, :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def user_signed_in?
    current_user.present?
  end

  def authenticate_user
    unless user_signed_in?
      redirect_to login_path, notice: "You must be signed in to continue."
    end
  end

  def log_in_user(user)
    session[:user_id] = user.id
  end

  def log_out_user
    session[:user_id] = nil
  end

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :authenticate_user
  helper_method :log_in_user
  helper_method :log_out_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @idea = Idea.find(params[:idea_id])
    @comment = @idea.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @idea, notice: "Comment posted"
    else
      render "ideas/show"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/idea_members_controller.rb
class IdeaMembersController < ApplicationController
  before_action :authenticate_user

  def create
    idea                      = Idea.find(params[:idea_id])
    idea_membership           = IdeaMember.new
    idea_membership.idea      = idea
    idea_membership.user      = current_user
    if idea_membership.save
      #flash[:notice] = "Joined idea"
    else
      flash[:danger] = "Something went wrong joining this idea."
    end
    redirect_to :back
  end

  def destroy
    idea                      = Idea.find(params[:idea_id])
    current_user.idea_members.find(params[:id]).destroy
    #flash[:notice] = "You left this idea"
    redirect_to :back
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  def new
    authenticate_user
    @idea = Idea.new
  end

  def create
    # TODO: tweak redirects for modal
    @idea = Idea.new(idea_params)
    @idea.user = current_user
    if @idea.save
      redirect_to @idea, notice: "Idea submitted!"
    else
      render :new
    end
  end

  def index
    @idea = Idea.new
    @ideas = Idea.all_by_date
  end

  def show
    @idea ||= Idea.find(params[:id])
    @comment = @idea.comments.new
  end

  def edit
    @idea = current_user.ideas.find(params[:id])
  end

  def update
    @idea ||= Idea.find(params[:id])
    if @idea.update(idea_params)
      redirect_to @idea, notice: "Idea updated"
    else
      render :edit
    end
  end

  def destroy
    @idea = current_user.ideas.find(params[:id])
    if @idea
      @idea.destroy
      redirect_to root_path, notice: "Idea deleted"
    else
      flash[:danger] = "error deleting idea"
      redirect_to @idea_path
    end
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :description, :image)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user

  def create
    idea                      = Idea.find(params[:idea_id])
    like                      = Like.new
    like.idea                 = idea
    like.user                 = current_user
    if like.save
      # flash[:notice] = "Liked"
      redirect_to :back
    else
      flash[:danger] = "Something went wrong liking this idea."
      redirect_to :back
    end
  end

  def destroy
    idea                      = Idea.find(params[:idea_id])
    current_user.likes.find(params[:id]).destroy
    # flash[:notice] = "Unliked"
    redirect_to :back
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_username(params[:username])
    if @user && @user.authenticate(params[:password])
      log_in_user(@user)
      redirect_to @user, notice: "Welcome back, #{@user.username}! What's your big idea today?"
    else
      flash[:danger] = "Invalid credentials."
      render :new
    end
  end

  def destroy
    log_out_user
    redirect_to root_path, notice: "See you next time!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_by_id, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in_user(@user)
      redirect_to @user, notice: "Welcome to the site!"
    else
      render :new
    end
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_by_id
    @user ||= User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/idea_members_helper.rb
module IdeaMembersHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.slim
- if @idea.errors.any?
  div class="alert alert-danger"
    p Oops! There were some errors:
    p = @idea.errors.full_messages.join(", ")


/ NOTE: multipart is required for carrierwave
= form_for @idea, html: { multipart: true } do |f|
  div class="form-group"
    = f.label :title
    = f.text_field :title, class: "form-control"

  div class="form-group"
    = f.label :description
    = f.text_area :description, class: "form-control"

  div class="form-group"
    = f.label :image, "Image (optional)"
    = f.file_field :image

  div class="form-group"
    = f.submit "Post", class: "btn btn-success"

app/views/ideas/edit.html.slim
h1 Edit Idea

= render "form"

app/views/ideas/index.html.slim
div class="container-fluid"
  div class="col-xs-6"
    h1 Ideas
  div class="col-xs-6"
    div class="pull-right"
      = link_to "New Idea", "#", class: "btn btn-default", data: { toggle: "modal", target: "#new-idea-modal" }

div class="modal fade" id="new-idea-modal" tabindex="-1"
  div class="modal-dialog"
    div class="modal-content"
      div class="modal-header"
        button type="button" class="close" data-dismiss="modal"
          span &times;
        h4 class="modal-title" New Idea
      div class="modal-body"
        - if user_signed_in?
          = render "ideas/form"
        - else
          p You must be #{link_to "signed in", login_path} to continue.

div class="container-fluid"
  - @ideas.each do |idea|
    div class="panel-idea"
      h4 = link_to idea.title, idea
      p = idea.description_truncate 250
      div class="tools"
        p by #{link_to idea.creator_username, idea.creator_user}

        - if user_signed_in? && idea.members_include?(current_user)
          = link_to "Leave", idea_idea_member_path(idea, idea.membership_for(current_user)), class: "btn btn-info", method: :delete
        - elsif current_user != idea.user
          = link_to "Join", idea_idea_members_path(idea), class: "btn btn-info", method: :post
        span &nbsp;&nbsp;&nbsp;
        - if user_signed_in? && idea.liked_by?(current_user)
          = link_to "Unlike", idea_like_path(idea, idea.like_for(current_user)), class: "btn btn-danger", method: :delete
        - elsif current_user != idea.user
          = link_to "Like", idea_likes_path(idea), class: "btn btn-danger", method: :post

        div class="pull-right"
          p
            = "<strong>Members:</strong> #{idea.num_members}".html_safe
            = " • "
            = "<strong>Likes:</strong> #{idea.num_likes}".html_safe

        div class="clearfix"

app/views/ideas/new.html.slim
h1 What's the big idea?
= render "form"

app/views/ideas/show.html.slim
div class="panel-idea"
  h1 = link_to @idea.title, @idea
  p = @idea.description_truncate 250

  - if @idea.image?
    p = image_tag @idea.image.url, width: 200


  div class="tools"
    p
      strong by #{link_to @idea.creator_username, @idea.creator_user}

    - if user_signed_in? && @idea.members_include?(current_user)
      = link_to "Leave", idea_idea_member_path(@idea, @idea.membership_for(current_user)), class: "btn btn-info", method: :delete
    - elsif current_user != @idea.user
      = link_to "Join", idea_idea_members_path(@idea), class: "btn btn-info", method: :post
    span &nbsp;&nbsp;&nbsp;
    - if user_signed_in? && @idea.liked_by?(current_user)
      = link_to "Unlike", idea_like_path(@idea, @idea.like_for(current_user)), class: "btn btn-danger", method: :delete
    - elsif current_user != @idea.user
      = link_to "Like", idea_likes_path(@idea), class: "btn btn-danger", method: :post
    span &nbsp;&nbsp;&nbsp;

    - if can? :manage, @idea
      = link_to "edit", edit_idea_path(@idea)
      span &nbsp;&nbsp;&nbsp;
      = link_to "delete", idea_path(@idea), method: :delete, data: { confirm: "Really delete this idea?" }

    div class="pull-right"
      p
        = "<strong>Members:</strong> #{@idea.num_members}".html_safe
        = " • "
        = "<strong>Likes:</strong> #{@idea.num_likes}".html_safe

    div class="clearfix"



/ TODO: tool partials



/ TODO: comment partials
h3 Comments
- if user_signed_in? && current_user != @idea.user
  h2 New Comment
  - if @comment.errors.any?
    div class="alert alert-danger"
      p = @comment.errors.full_messages.join(", ")
  = form_for [@idea, @comment] do |f|
    div class="form-group"
      = f.label :body
      = f.text_area :body, class: "form-control"
    div class="form-group"
      = f.submit "Post Comment", class: "btn btn-success"
- elsif current_user == @idea.user
  p
- else
  p You must be logged in to post new comments.

- @idea.comments_by_date.each do |comment|
  div class="well"
    p = "<strong>#{comment.user.username}</strong> on <strong>#{comment.created_at.to_formatted_s(:long_ordinal)}</strong>".html_safe
    p = comment.body
    / TODO: comment CRUD

app/views/layouts/application.html.slim
doctype html
html
  head
    title Idea Factory
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    div class="container-fluid"
      / navbar
      / TODO: partials
      div class="navbar navbar-default"
        div class="navbar-header"
          = link_to "Idea Factory", root_path, class: "navbar-brand"
        ul class="nav navbar-nav pull-right"
          li
            = link_to "<strong>Ideas</strong>".html_safe, ideas_path
          - if user_signed_in?
            li = link_to "Hello, #{current_user.username}", current_user
            li = link_to "Log Out", logout_path, method: :delete
          - else
            li = link_to "Log In", login_path
            li = link_to "Sign Up", signup_path

      / the flash
      - if flash[:notice]
        div class="alert alert-info"
          p = flash[:notice]

      - elsif flash[:danger]
        div class="alert alert-danger"
          p = flash[:danger]

      / body
      == yield

app/views/users/new.html.slim
h1 Sign Up

- if @user.errors.any?
  div class="alert alert-danger"
    p Oops! There were some errors:
    p = @user.errors.full_messages.join(", ")

div
  = form_for @user do |f|
    div class="form-group"
      = f.label :username
      = f.text_field :username, class: "form-control"

    div class="form-group"
      = f.label :email
      = f.text_field :email, class: "form-control"

    div class="form-group"
      = f.label :password
      = f.password_field :password, class: "form-control"

    div class="form-group"
      = f.label :password_confirmation
      = f.password_field :password_confirmation, class: "form-control"

    div class="form-group"
      = f.submit "Sign up", class: "btn btn-success"

app/views/users/show.html.slim
h1 = @user.username
strong
  = mail_to @user.email

h2 Ideas
p = link_to "Create a new idea", new_idea_path, class: "btn btn-default"

- if @user.ideas.any?
  - @user.ideas.each do |idea|
    div class="well"
      p = link_to idea.title, idea

- else
  p You've got no ideas - that can't be true!
  p = link_to "Create a new idea", new_idea_path, class: "btn btn-default"